# Generated by Django 5.1 on 2025-02-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='unique_url',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
