# Generated by Django 5.1 on 2025-02-17 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_unique_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unique_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
