# Generated by Django 5.1 on 2025-02-16 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_deleted',
            new_name='is_deleted_for_all',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
