# Generated by Django 5.1 on 2025-02-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='friendship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='user.friendship'),
        ),
    ]
